name = "www-dantuck"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[vars]
GITHUB_REPO = "dantuck/www.dantuck.com"
CF_ACCOUNT_ID = "8c84992709d375b2c9bba48b7e8a2361"
CF_PAGES_PROJECT = "www-dantuck"
