---
label: recipe
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: list
  name: tags
  label: tags
- type: text
  name: author
  label: author
- type: text
  name: prepTime
  label: prepTime
- type: text
  name: cookTime
  label: cookTime
- type: list
  name: ingredients
  label: ingredients
- type: text
  name: description
  label: description
- type: boolean
  name: resizeImages
  label: resizeImages
